site:
  name: さとう数理塾
  site: 'https://stsrjk.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

social:
  instagram: 'https://www.instagram.com/satosurijyuku/'

# Default SEO metadata
metadata:
  title:
    default: さとう数理塾
    template: '%s — さとう数理塾'
  description: 'AI教材と講師サポートで学ぶ、沼津の数学・理系専門の個別指導塾。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: さとう数理塾
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: ja
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: 'G-F7GL0JEEMD'
      partytown: false

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
